eureka:
  client:
     registerWithEureka: false
     fetch-registry: false
     server:
      waitTimeInMsWhenSyncEmpty: 0
        

server:
  port: 8761
  
  
spring:
  application:
    name: AMAZON-SERVER